### PR TITLE
Removing deprecated FloatMath.

### PR DESCRIPTION
**Pull request by jp2014**
FloatMath methods have been deprecated and are removed in API 23.

### CODE REVIEW

**Comment by calvarez-ov** [comment]
Any chance of merging this?

**Comment by rock3r** [comment]
This shouldn't be needed. The library targets and is built with SDK 22, which still has the methods and will build. You only need to do this if you copy-paste the library code and use it in a project compiled with SDK > 22, but at that point it's on you, and that is when you need to fix it.

The library as is works perfectly fine: methods are in fact still there, just marked as `@remove`d so that you can't use them with `compileSdk 23`, which we don't and won't ever have. See [the `FloathMath` source](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/util/FloatMath.java) for details.

**Comment by calvarez-ov** [comment]
Why not merge it though?  That way users won't have to add a proguard rule to ignore the warning.

**Comment by rock3r** [comment]
Because two reasons:

1) That would require a new deploy to Bintray to have any effect, and I have no time to do it. Consider also this library has basically been deprecated since this view isn't in AOSP anymore!
2) This library is a straight backport of AOSP code. I've always avoided changing anything that wasn't _strictly_ needed to get it to build, as the goal is not to adopt and thus maintain a fork of AOSP code This is not strictly needed.

**Pull request closed without merging**
