### PR TITLE
Remove uppercase letters in packagename

### PR DESCRIPTION
**Pull request by ncornette**
IntelliJ IDEA reports a bad package name in the source code because of uppercase letters in the name of the directory. This removes the warning.

### CODE REVIEW

**Comment by rock3r** [comment]
@ncornette I'm taking the chance to update the build configuration (the one in the project won't work on AS 1.x) and rename the modules as well. The folder names will be changed to reflect the actual package names, which is lowercase.

**Comment by ncornette** [comment]
Great :-)

**Comment by rock3r** [comment]
I've tagged v2.1.1 on the master branch; it should become available on `jcenter()` soon (had to go through manual approval as I fixed the group name for the release to maven repo).

**Comment by ncornette** [comment]
I rebased my branch, thanks !

**Pull request closed without merging**
